name: PR Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14.5, 1.15.1, 1.16.2]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go version
          make build
      - name: Tests
        run: |
          make test
